# Generated by Django 4.0.4 on 2022-05-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('tokenID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('accessToken', models.CharField(max_length=255)),
                ('refreshToken', models.CharField(max_length=255)),
                ('clientID', models.CharField(max_length=255)),
                ('clientSecret', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=255)),
                ('lastUpdatedTime', models.DateTimeField()),
                ('expiresIn', models.IntegerField()),
            ],
        ),
    ]
